In [1]:
import pandas as pd
import numpy as np 
from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer, String, MetaData, ForeignKey
from sqlalchemy import inspect
from sqlalchemy import MetaData
import sqlite3
import datetime
import sqlalchemy

Limpieza de datos 
EXTRACCION

In [4]:
dfHA = pd.read_csv("Building_Permits.csv")
dfHA.head(10)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (22,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380611e+12
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420164e+12
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.424857e+12
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.443574e+12
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.445482e+11
5,201706149344,8,otc alterations permit,06/14/2017,4105,009,800,NaN,Indiana,St,...,1.0,constr type 1,1.0,constr type 1,NaN,10.0,Potrero Hill,94107.0,"(37.75922331346539, -122.39170402628598)",1.466911e+12
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,NaN,11th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)",1.468970e+12
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,NaN,Revere,Av,...,NaN,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)",1.469035e+12
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,NaN,Fell,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)",1.469198e+12
9,M804767,8,otc alterations permit,07/06/2017,1259,016,89,NaN,Alpine,Tr,...,NaN,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117.0,"(37.7691724293766, -122.43734859051908)",1.469324e+11

transformacion de datos

In [5]:
dfHA.dropna().isnull()
dfHA.head(10)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380611e+12
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420164e+12
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.424857e+12
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.443574e+12
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.445482e+11
5,201706149344,8,otc alterations permit,06/14/2017,4105,009,800,NaN,Indiana,St,...,1.0,constr type 1,1.0,constr type 1,NaN,10.0,Potrero Hill,94107.0,"(37.75922331346539, -122.39170402628598)",1.466911e+12
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,NaN,11th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)",1.468970e+12
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,NaN,Revere,Av,...,NaN,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)",1.469035e+12
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,NaN,Fell,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)",1.469198e+12
9,M804767,8,otc alterations permit,07/06/2017,1259,016,89,NaN,Alpine,Tr,...,NaN,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117.0,"(37.7691724293766, -122.43734859051908)",1.469324e+11

llenar datos faltantes

In [6]:
dfHA.fillna(method='bfill', axis=0).fillna(0)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,A,Ellis,St,...,3.0,constr type 3,1.0,constr type 1,Y,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380611e+12
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,A,Geary,St,...,3.0,constr type 3,1.0,constr type 1,Y,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420164e+12
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,A,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,Y,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.424857e+12
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,A,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),Y,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.443574e+12
4,201611283529,6,demolitions,11/28/2016,0342,001,950,A,Market,St,...,3.0,constr type 3,1.0,constr type 1,Y,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.445482e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164497,201612013946,8,otc alterations permit,12/01/2016,0513,010,2490,0,Filbert,St,...,5.0,wood frame (5),5.0,wood frame (5),0,2.0,Marina,94123.0,"(37.79770949836049, -122.44037643532758)",1.446041e+11
164498,201612013904,8,otc alterations permit,12/01/2016,3642,019,3266,0,24th,St,...,5.0,wood frame (5),5.0,wood frame (5),0,9.0,Mission,94110.0,"(37.75249406266713, -122.41781004248826)",1.445982e+12
164499,201612024079,8,otc alterations permit,12/02/2016,1805,016,1473,0,48th,Av,...,5.0,wood frame (5),5.0,wood frame (5),0,4.0,Sunset/Parkside,94122.0,"(37.758972810340175, -122.50830114426145)",1.446222e+12
164500,201612074396,8,otc alterations permit,12/07/2016,0596,002,1849,0,Larkin,St,...,5.0,wood frame (5),5.0,wood frame (5),0,3.0,Russian Hill,94109.0,"(37.794990980504, -122.42020070167871)",1.446675e+12
164501,201612074397,8,otc alterations permit,12/07/2016,0596,002,1849,0,Larkin,St,...,5.0,wood frame (5),5.0,wood frame (5),0,3.0,0,0.0,0,0.000000e+00

Identificacionde registros duplicados

In [7]:
dfHA.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

Eliminacion

In [8]:
dfHA.drop_duplicates()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380611e+12
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420164e+12
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.424857e+12
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.443574e+12
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.445482e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164497,201612013946,8,otc alterations permit,12/01/2016,0513,010,2490,NaN,Filbert,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.79770949836049, -122.44037643532758)",1.446041e+11
164498,201612013904,8,otc alterations permit,12/01/2016,3642,019,3266,NaN,24th,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94110.0,"(37.75249406266713, -122.41781004248826)",1.445982e+12
164499,201612024079,8,otc alterations permit,12/02/2016,1805,016,1473,NaN,48th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94122.0,"(37.758972810340175, -122.50830114426145)",1.446222e+12
164500,201612074396,8,otc alterations permit,12/07/2016,0596,002,1849,NaN,Larkin,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Russian Hill,94109.0,"(37.794990980504, -122.42020070167871)",1.446675e+12
164501,201612074397,8,otc alterations permit,12/07/2016,0596,002,1849,NaN,Larkin,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,NaN,NaN,NaN,NaN

eliminacion de espacion en blanco

In [9]:
dfHA.replace(' ','')
dfHA.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380611e+12
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420164e+12
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.424857e+12
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.443574e+12
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.445482e+11

cambio de case

In [12]:
dfHA['Description'] = dfHA['Description'].str.upper()
dfHA['Permit Type Definition'] = dfHA['Permit Type Definition'].str.upper()
dfHA['Street Name'] = dfHA['Street Name'].str.upper()
dfHA['Neighborhoods - Analysis Boundaries'] = dfHA['Neighborhoods - Analysis Boundaries'].str.upper()
dfHA['Existing Construction Type Description'] = dfHA['Existing Construction Type Description'].str.upper()
dfHA['Proposed Construction Type Description'] = dfHA['Proposed Construction Type Description'].str.upper()
dfHA['Current Status'] = dfHA['Current Status'].str.upper()
dfHA['Existing Use'] = dfHA['Existing Use'].str.upper()
dfHA.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,SIGN - ERECT,05/06/2015,0326,023,140,NaN,ELLIS,St,...,3.0,CONSTR TYPE 3,NaN,NaN,NaN,3.0,TENDERLOIN,94102.0,"(37.785719256680785, -122.40852313194863)",1.380611e+12
1,201604195146,4,SIGN - ERECT,04/19/2016,0306,007,440,NaN,GEARY,St,...,3.0,CONSTR TYPE 3,NaN,NaN,NaN,3.0,TENDERLOIN,94102.0,"(37.78733980600732, -122.41063199757738)",1.420164e+12
2,201605278609,3,ADDITIONS ALTERATIONS OR REPAIRS,05/27/2016,0595,203,1647,NaN,PACIFIC,Av,...,1.0,CONSTR TYPE 1,1.0,CONSTR TYPE 1,NaN,3.0,RUSSIAN HILL,94109.0,"(37.7946573324287, -122.42232562979227)",1.424857e+12
3,201611072166,8,OTC ALTERATIONS PERMIT,11/07/2016,0156,011,1230,NaN,PACIFIC,Av,...,5.0,WOOD FRAME (5),5.0,WOOD FRAME (5),NaN,3.0,NOB HILL,94109.0,"(37.79595867909168, -122.41557405519474)",1.443574e+12
4,201611283529,6,DEMOLITIONS,11/28/2016,0342,001,950,NaN,MARKET,St,...,3.0,CONSTR TYPE 3,NaN,NaN,NaN,6.0,TENDERLOIN,94102.0,"(37.78315261897309, -122.40950883997789)",1.445482e+11

llena de datos completos

In [13]:
dfHA['Fire Only Permit'] = dfHA['Fire Only Permit'].fillna('N')
dfHA['Unit'] = dfHA['Unit'].fillna('0')
print(dfHA['Fire Only Permit'])

0         N
1         N
2         N
3         N
4         N
         ..
164497    N
164498    N
164499    N
164500    N
164501    N
Name: Fire Only Permit, Length: 164502, dtype: object

eliminacionde colunmas no  necesarias

In [14]:
dfHA = dfHA.drop(columns=['Site Permit'])
dfHA = dfHA.drop(columns=['TIDF Compliance'])
dfHA = dfHA.drop(columns=['Street Number Suffix'])
dfHA = dfHA.drop(columns=['Structural Notification'])
dfHA = dfHA.drop(columns=['Existing Units'])
dfHA = dfHA.drop(columns=['Voluntary Soft-Story Retrofit'])
dfHA = dfHA.drop(columns=['Proposed Construction Type'])
dfHA = dfHA.drop(columns=['Unit Suffix'])

dfHA.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Street Suffix,Unit,...,Proposed Units,Plansets,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type Description,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,SIGN - ERECT,05/06/2015,0326,023,140,ELLIS,St,0,...,NaN,2.0,3.0,CONSTR TYPE 3,NaN,3.0,TENDERLOIN,94102.0,"(37.785719256680785, -122.40852313194863)",1.380611e+12
1,201604195146,4,SIGN - ERECT,04/19/2016,0306,007,440,GEARY,St,0.0,...,NaN,2.0,3.0,CONSTR TYPE 3,NaN,3.0,TENDERLOIN,94102.0,"(37.78733980600732, -122.41063199757738)",1.420164e+12
2,201605278609,3,ADDITIONS ALTERATIONS OR REPAIRS,05/27/2016,0595,203,1647,PACIFIC,Av,0,...,39.0,2.0,1.0,CONSTR TYPE 1,CONSTR TYPE 1,3.0,RUSSIAN HILL,94109.0,"(37.7946573324287, -122.42232562979227)",1.424857e+12
3,201611072166,8,OTC ALTERATIONS PERMIT,11/07/2016,0156,011,1230,PACIFIC,Av,0.0,...,1.0,2.0,5.0,WOOD FRAME (5),WOOD FRAME (5),3.0,NOB HILL,94109.0,"(37.79595867909168, -122.41557405519474)",1.443574e+12
4,201611283529,6,DEMOLITIONS,11/28/2016,0342,001,950,MARKET,St,0,...,NaN,2.0,3.0,CONSTR TYPE 3,NaN,6.0,TENDERLOIN,94102.0,"(37.78315261897309, -122.40950883997789)",1.445482e+11

contar valores faltantes

In [15]:
dfHA.isnull().sum()

Permit Number                                 0
Permit Type                                   0
Permit Type Definition                        0
Permit Creation Date                          0
Block                                         0
Lot                                           0
Street Number                                 0
Street Name                                   0
Street Suffix                              2310
Unit                                          0
Description                                 256
Current Status                                0
Current Status Date                           0
Filed Date                                    0
Issued Date                               10016
Completed Date                            79709
First Construction Document Date          10028
Number of Existing Stories                37401
Number of Proposed Stories                37634
Fire Only Permit                              0
Permit Expiration Date                    42621
Estimated Cost                            33532
Revised Cost                               4253
Existing Use                              36038
Proposed Use                              37271
Proposed Units                            44211
Plansets                                  32939
Existing Construction Type                37901
Existing Construction Type Description    37901
Proposed Construction Type Description    37880
Supervisor District                        1603
Neighborhoods - Analysis Boundaries        1610
Zipcode                                    1604
Location                                   1591
Record ID                                     1
dtype: int64

In [17]:
df = pd.DataFrame(dfHA)

df_re = df[['Zipcode','Location']]
df_re['id_Permit'] = df_re.index
df_re['id_Record'] = df_re.index
df_re['Neighborhoods_Analysis'] = df_re.index
df_re.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Zipcode,Location,id_Permit,id_Record,Neighborhoods_Analysis
0,94102.0,"(37.785719256680785, -122.40852313194863)",0,0,0
1,94102.0,"(37.78733980600732, -122.41063199757738)",1,1,1
2,94109.0,"(37.7946573324287, -122.42232562979227)",2,2,2
3,94109.0,"(37.79595867909168, -122.41557405519474)",3,3,3
4,94102.0,"(37.78315261897309, -122.40950883997789)",4,4,4

In [18]:
df = pd.DataFrame(dfHA)

df_per = df[['Permit Number','Permit Type','Permit Type Definition','Permit Creation Date']]
df_per.columns = ['Permit_Number','Permit_Type','Permit_Type_Definition','Permit_Creation_Date']
df_per['id_street'] = df_per.index

df_per.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,Permit_Number,Permit_Type,Permit_Type_Definition,Permit_Creation_Date,id_street
0,201505065519,4,SIGN - ERECT,05/06/2015,0
1,201604195146,4,SIGN - ERECT,04/19/2016,1
2,201605278609,3,ADDITIONS ALTERATIONS OR REPAIRS,05/27/2016,2
3,201611072166,8,OTC ALTERATIONS PERMIT,11/07/2016,3
4,201611283529,6,DEMOLITIONS,11/28/2016,4